[package]
name = "rusted-punk"
version = "0.1.0"
authors = ["Benedikt <Sayrin@web.de>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.118", features = ["derive"] }
toml = "0.5.8"
serde_with = "1.6.0"

[dev-dependencies]
tempfile = "3.1.0"
